name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: Code formatting
        run: go fmt .
      - name: Helps identify and fix errors in Go code
        run: go vet .
      - name: Test with the Go CLI
        run: go test -v .